### ISSUE TITLE
WiFi boards aren't showing up during peripheral scan

### ISSUE THREAD

**Issue by BlitzCityDIY** [adafruit/PyLeap-Android#4]
In the newest version (V1.0.1 b4) I'm not seeing any WiFi boards show up during the scan. Before updating they were showing up. I confirmed they are discoverable on my network by checking circuitpython.local. BLE peripherals are connecting properly.

**Comment by antonio-openroad** [comment]
Could you test a couple of things to get a better understanding of the problem:

1 - Reset the Wifi board, and check if the board is visible after power up
2 - Reset the Android device
3 - Check that Wifi is enabled on the phone and using the same network that the Wifi board

Please let me know if the Wifi board appears or still not visible.
Thanks for the report.

**Comment by BlitzCityDIY** [comment]
@antonio-openroad ah, rebooting the phone worked!
